#!/bin/bash
set -e
battery=/sys/class/power_supply/BAT0
for option in energy charge ; do
    read cur < "$battery/${option}_now" || true
    read max < "$battery/${option}_full" || true
done

if [[ $cur -gt 0 ]] && [[ $max -gt 0 ]] ; then
    printf '%d%%' $((100 * $cur/$max))
else
    printf -- '--%%'
fi

read charging < "$battery/status"
case $charging in
    Charging|Full)
        symbol=⚡
        ;;
    Discharging)
        symbol=' '
        ;;
    Unknown)
        symbol='?'
        ;;
esac

printf " [%s]" "$symbol"

printf ' | '

date "+%d %b %H:%M"
